---
title: "Experience"
---

<br><br>

### Education

- **Ph.D. in Mathematics, [Tsinghua University](https://www.tsinghua.edu.cn/en/), 2015-2020**
  - [School of Sciences, Department of Mathematics](https://www.math.tsinghua.edu.cn/#)
    - Advisor: [Prof. Stephen S.-T. Yau](http://homepages.math.uic.edu/~yau/)
- **B.Sc. in Mathematics, [Sun Yat-sen University](https://www.sysu.edu.cn/sysuen/index.htm), 2011-2015**
  - [School of Mathematics, Department of Mathematics and Applied Mathematics](https://math.sysu.edu.cn/page/25)
    - Major: Mathematics
    - Advisor: [Prof. Lihua Yang](https://math.sysu.edu.cn/teacher/634) and [Prof. Daoqing Dai](https://scholar.google.com/citations?user=wghJ4rkAAAAJ&hl=zh-CN)
  - [Yat-sen School](https://baike.baidu.com/item/中山大学逸仙学院/56627027)
    - Major: Statistics
  - [Lingnan College](https://lingnan.sysu.edu.cn/en)
    - Minor: Finance

### Professional Training

- **Postdoctoral Research Scientist, March 2023 - September 2024**
  - [The Center of Statistical Genetics, Gertrude H. Sergievsky Center, and the Department of Neurology, Columbia University Irving Medical Center](https://www.neurology.columbia.edu/research/research-centers-and-programs/center-statistical-genetics)
  - Mentors: [Prof. Suzanne M. Leal](https://www.neurology.columbia.edu/profile/suzanne-m-leal-phd) and [Prof. Gao T. Wang](https://www.tigerwang.org)
- **Postdoctoral Research Scientist, August 2020 - January 2023**
  - [The Yau Mathematical Sciences Center, Tsinghua University](https://ymsc.tsinghua.edu.cn/en/), and [Yanqi Lake Beijing Institute of Mathematical Sciences and Applications](https://www.bimsa.cn)
  - Mentor: [Prof. Donald Rubin](https://statistics.fas.harvard.edu/people/donald-b-rubin)
- **Research Assistant, November 2018 - January 2023**
  - [The Yau Mathematical Sciences Center, Tsinghua University](https://ymsc.tsinghua.edu.cn/en/)
  - Mentor: [Prof. Donald Rubin](https://statistics.fas.harvard.edu/people/donald-b-rubin)

### Academic Positions
- **Instructor, October 2024-present**
  - [The Center of Statistical Genetics, Gertrude H. Sergievsky Center, and the Department of Neurology, Columbia University Irving Medical Center](https://www.neurology.columbia.edu/research/research-centers-and-programs/center-statistical-genetics)

### Honors and Awards

- **2023:** Top Poster Prize for Postdoc Research Symposium at Columbia University
- **2022:** [ICCM Best Thesis Award (Doctoral Thesis Award) Silver Prize](http://www.yau-bta.com/en/show-86-37.html)
- **2022:** Ruolin Prize of Yau Mathematical Sciences Center, Tsinghua University
- **2020:** Outstanding Graduate of Beijing
- **2018-2019:** First Prize Scholarship of Tsinghua University
- **2016:** Excellent Teaching Assistant at Tsinghua University
- **2015-2020:** Scholarship of Yau Mathematical Sciences Center
- **2012-2014:** Honorable Mention in [the Mathematical Contest in Modeling](https://www.comap.com/contests/mcm-icm)
- **2011-2015:** First Prize Scholarship of Sun Yat-sen University